from django.db import models

# Create your models here.

class catobjetivo(models.Model):
    cveobjetivo = models.CharField(max_length=8)
    cveestrategia = models.CharField(max_length=1)
    cvelineaaccion = models.CharField(max_length=1)
    descripcion = models.CharField(max_length=250)
    estatus = models.CharField(max_length=1)

class catareas(models.Model):
    cvedireccion=models.CharField(max_length=2)
    cvesubdireccion=models.CharField(max_length=2)
    cvedepto=models.CharField(max_length=2)
    cvearea=models.CharField(max_length=2)
    descripcion=models.CharField(max_length=80)
    estatus=models.CharField(max_length=1)

class catprogramas(models.Model):
    cveprograma=models.CharField(max_length=2, primary_key=True)
    descripcion=models.CharField(max_length=30)
    objetivo=models.CharField(max_length=250)
    techofinanciero=models.CharField(max_length=30)
    estatus=models.CharField(max_length=1)

class catfuentefinancia(models.Model):
    cvefuente=models.CharField(max_length=2, primary_key=True)
    descripcion=models.CharField(max_length=30)
    estatus=models.CharField(max_length=1)

class catUmedidas(models.Model):
    cveunidad=models.CharField(max_length=4, primary_key=True)
    descripcion=models.CharField(max_length=30)
    estatus=models.CharField(max_length=1)

class cattipomedicion(models.Model):
    cvetipomedicion=models.CharField(max_length=2, primary_key=True)
    descripcion=models.CharField(max_length=30)
    estatus=models.CharField(max_length=1)

class catestatus(models.Model):
    cveestatus=models.CharField(max_length=2, primary_key=True)
    descripcion=models.CharField(max_length=30)
    estatus=models.CharField(max_length=1)

class catumbral(models.Model):
    
    cveumbral=models.CharField(max_length=2, primary_key=True)
    limite1inferior=models.FloatField()
    limite1superior=models.FloatField()
    limite2inferior=models.FloatField()
    limite2superior=models.FloatField()
    limite3inferior=models.FloatField()
    limite3superior=models.FloatField()
estatus=models.CharField(max_length=1)

class catusuarios(models.Model):
    cvecuenta=models.CharField(max_length=6, primary_key=True)
    nombre=models.CharField(max_length=35)
    paterno=models.CharField(max_length=35)
    materno=models.CharField(max_length=35)
    sexos=[
        ('F','Femenino'),
        ('M','Masculino')
    ]
    sexo=models.CharField(max_length=1,choices=sexos,default='F')
    telefono=models.CharField(max_length=10)
    correo=models.EmailField()
    fecharegistro=models.DateTimeField(auto_now_add=True)
    password=models.CharField(max_length=15)
    activo=models.BooleanField(default=True)

class DBproyectos(models.Model):
    anio=models.CharField(max_length=4, primary_key=True)
    cvedireccion=models.CharField(max_length=2)
    cvesubdireccion=models.CharField(max_length=2)
    cvedepto=models.CharField(max_length=2)
    cvearea=models.CharField(max_length=2)
    secuencia=models.CharField(max_length=2)
    descripcionactividad=models.CharField(max_length=250)
    cveprogramapresup=models.CharField(max_length=2)
    cveobjetivo=models.CharField(max_length=8)
    cveestrategia=models.CharField(max_length=1)
    cvelineaaccion=models.CharField(max_length=1)
    cvefuente=models.CharField(max_length=2)
    cantidadtotalfisica=models.FloatField()
    cveunidadmedida=models.CharField(max_length=4)
    cantidadbeneficiarios=models.FloatField()
    cveunidadbeneficiarios=models.CharField(max_length=4)
    cvetipomedicion=models.CharField(max_length=1)
    montototalprogramado=models.FloatField()
    resumennarrativo=models.CharField(max_length=250)
    metaprogramada01=models.FloatField()
    metarealizada01=models.FloatField()
    montoprogramado01=models.FloatField()
    montorealizado01=models.FloatField()
    metaprogramada02=models.FloatField()
    metarealizada02=models.FloatField()
    montoprogramado02=models.FloatField()
    montorealizado02=models.FloatField()
    metaprogramada03=models.FloatField()
    metarealizada03=models.FloatField()
    montoprogramado03=models.FloatField()
    montorealizado03=models.FloatField()
    metaprogramada04=models.FloatField()
    metarealizada04=models.FloatField()
    montoprogramado04=models.FloatField()
    montorealizado04=models.FloatField()
    metaprogramada05=models.FloatField()
    metarealizada05=models.FloatField()
    montoprogramado05=models.FloatField()
    montorealizado05=models.FloatField()
    metaprogramada06=models.FloatField()
    metarealizada06=models.FloatField()
    montoprogramado06=models.FloatField()
    montorealizado06=models.FloatField()
    metaprogramada07=models.FloatField()
    metarealizada07=models.FloatField()
    montoprogramado07=models.FloatField()
    montorealizado07=models.FloatField()
    metaprogramada08=models.FloatField()
    metarealizada08=models.FloatField()
    montoprogramado08=models.FloatField()
    montorealizado08=models.FloatField()
    metaprogramada09=models.FloatField()
    metarealizada09=models.FloatField()
    montoprogramado09=models.FloatField()
    montorealizado09=models.FloatField()
    metaprogramada10=models.FloatField()
    metarealizada10=models.FloatField()
    montoprogramado10=models.FloatField()
    montorealizado10=models.FloatField()
    metaprogramada11=models.FloatField()
    metarealizada11=models.FloatField()
    montoprogramado11=models.FloatField()
    montorealizado11=models.FloatField()
    metaprogramada12=models.FloatField()
    metarealizada12=models.FloatField()
    montoprogramado12=models.FloatField()
    montorealizado12=models.FloatField()
    fecharegistro=models.DateTimeField(auto_now_add=True)